### ISSUE TITLE
"time does not match format" exception

### ISSUE THREAD

**Issue by Gim6626** [foss-news/fossnewsbot#24]
Trace:
```
fossnewsbot        | 2021-11-20 08:07:10,517 ERROR    bot - time data '2021-11-16T20:01:25.793220Z' does not match format '%Y-%m-%dT%H:%M:%S%z'
fossnewsbot        | 2021-11-20 08:07:10,538 ERROR    aiohttp.server - Error handling request
fossnewsbot        | Traceback (most recent call last):
fossnewsbot        |   File "/srv/fossnewsbot/fossnewsbot/handlers.py", line 183, in handler
fossnewsbot        |     await msg_next(callback)
fossnewsbot        |   File "/srv/fossnewsbot/fossnewsbot/handlers.py", line 101, in msg_next
fossnewsbot        |     text = format_news(news)
fossnewsbot        |   File "/srv/fossnewsbot/fossnewsbot/handlers.py", line 51, in format_news
fossnewsbot        |     dt = datetime.strptime(dt, '%Y-%m-%dT%H:%M:%S%z').strftime('%x')
fossnewsbot        |   File "/usr/local/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
fossnewsbot        |     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
fossnewsbot        |   File "/usr/local/lib/python3.9/_strptime.py", line 349, in _strptime
fossnewsbot        |     raise ValueError("time data %r does not match format %r" %
fossnewsbot        | ValueError: time data '2021-11-16T20:01:25.793220Z' does not match format '%Y-%m-%dT%H:%M:%S%z'
fossnewsbot        | 
fossnewsbot        | During handling of the above exception, another exception occurred:
fossnewsbot        | 
fossnewsbot        | Traceback (most recent call last):
fossnewsbot        |   File "/srv/fossnewsbot/venv/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 430, in _handle_request
fossnewsbot        |     resp = await request_handler(request)
fossnewsbot        |   File "/srv/fossnewsbot/venv/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
fossnewsbot        |     resp = await handler(request)
fossnewsbot        |   File "/srv/fossnewsbot/venv/lib/python3.9/site-packages/aiohttp/web_urldispatcher.py", line 954, in _iter
fossnewsbot        |     resp = await method()
fossnewsbot        |   File "/srv/fossnewsbot/venv/lib/python3.9/site-packages/aiogram/dispatcher/webhook.py", line 139, in post
fossnewsbot        |     results = await self.process_update(update)
fossnewsbot        |   File "/srv/fossnewsbot/venv/lib/python3.9/site-packages/aiogram/dispatcher/webhook.py", line 190, in process_update
fossnewsbot        |     return fut.result()
fossnewsbot        |   File "/srv/fossnewsbot/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
fossnewsbot        |     response = await handler_obj.handler(*args, **partial_data)
fossnewsbot        |   File "/srv/fossnewsbot/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
fossnewsbot        |     return await self.callback_query_handlers.notify(update.callback_query)
fossnewsbot        |   File "/srv/fossnewsbot/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
fossnewsbot        |     response = await handler_obj.handler(*args, **partial_data)
fossnewsbot        |   File "/srv/fossnewsbot/fossnewsbot/handlers.py", line 251, in handler
fossnewsbot        |     await error(callback)
fossnewsbot        |   File "/srv/fossnewsbot/fossnewsbot/handlers.py", line 135, in error
fossnewsbot        |     await callback.message.edit_text(text=text, disable_web_page_preview=True)
fossnewsbot        |   File "/srv/fossnewsbot/venv/lib/python3.9/site-packages/aiogram/types/message.py", line 2616, in edit_text
fossnewsbot        |     return await self.bot.edit_message_text(
fossnewsbot        |   File "/srv/fossnewsbot/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 2498, in edit_message_text
fossnewsbot        |     result = await self.request(api.Methods.EDIT_MESSAGE_TEXT, payload)
fossnewsbot        |   File "/srv/fossnewsbot/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 226, in request
fossnewsbot        |     return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
fossnewsbot        |   File "/srv/fossnewsbot/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
fossnewsbot        |     return check_result(method, response.content_type, response.status, await response.text())
fossnewsbot        |   File "/srv/fossnewsbot/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 115, in check_result
fossnewsbot        |     exceptions.BadRequest.detect(description)
fossnewsbot        |   File "/srv/fossnewsbot/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 140, in detect
fossnewsbot        |     raise err(cls.text or description)
fossnewsbot        | aiogram.utils.exceptions.CantParseEntities: Can't parse entities: character '-' is reserved and must be escaped with the preceding '\'
```

**Comment by Gim6626** [comment]
Была проблема в FNGS, он отдавал dt и gather_dt в разных форматах, исправил в https://taiga.permlug.org/project/fngs/issue/76, проблемы больше нет
